GET http://localhost:5000/notes

###
POST http://localhost:5000/add-note
Content-Type: application/json

{
    "judul": "Rapat basa-basi",
    "isi": "proker"
}
###
PUT http://localhost:5000/edit-note/1
Content-Type: application/json

{
    "judul": "Ramadhan",
    "isi": "Test 1234"
}
###
DELETE http://localhost:5000/delete-note/6

###
GET http://localhost:5000/notes